services:
  app:
    image: debian:latest
    command: /bin/sh -c "apt-get -qq update && apt-get -qq install -y wget && wget https://community-downloads.s3.us-east-2.amazonaws.com/documize-community-plus-linux-amd64 && chmod 777 ./documize-community-plus-linux-amd64 && ./documize-community-plus-linux-amd64"
    depends_on:
      - db
    ports:
      - 5001:5001
    environment:
      DOCUMIZEPORT: 5001
      DOCUMIZEDB: host=db port=5432 dbname=documize user=documize password=Passw0rd sslmode=disable
      DOCUMIZEDBTYPE: postgresql
      DOCUMIZESALT: hsk3Acndky8cdTNx3
      DOCUMIZELOCATION: selfhost
    networks:
      - documizenet

volumes:
  db-data:

networks:
  documizenet:
