version: '3.9'
services:
  resume:
    image: docker.io/amruthpillai/reactive-resume:latest
    container_name: resume
    restart: unless-stopped
    env_file: .env
    networks:
    - caddy
    - postgres
    - redis
    labels:
      traefik.enable: 'true'
      traefik.http.services.resume.loadbalancer.server.port: 3000
      traefik.http.routers.resume.rule: Host(`cv.marcpartensky.com`)
      traefik.http.routers.resume.entrypoints: web
  printer:
    image: docker.io/browserless/chrome:1.61.0-puppeteer-21.4.1
    container_name: printer
    restart: unless-stopped
    env_file: .env
    networks:
    - caddy
    environment:
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true
    labels:
      traefik.enable: 'true'
      traefik.http.services.printer.loadbalancer.server.port: 3000
      traefik.http.routers.printer.rule: Host(`printer.marcpartensky.com`)
      traefik.http.routers.printer.entrypoints: web
networks:
  caddy:
    external: true
  postgres:
    external: true
  redis:
    external: true
