version: "3.9"

services:
  oxivia:
    image: wordpress
    restart: unless-stopped
    env_file:
      - data/secrets/oxivia.env
    volumes:
      - $BIND_MOUNTS/oxivia:/var/www/html
      - ./data/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - caddy
      - nginx
      - oxivia
    depends_on:
      - oxivia_mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:80"]
    labels:
      caddy: oxivia.business.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.oxivia.rule: Host(`oxivia.business.marcpartensky.com`)
      traefik.http.routers.oxivia.entrypoints: websecure
      traefik.http.routers.oxivia.tls.certresolver: tls
      traefik.http.services.oxivia.loadbalancer.server.port: 80

  oxivia_mysql:
    image: mysql
    restart: unless-stopped
    env_file:
      - data/secrets/oxivia.env
    ports:
      - "3307:3306"
    volumes:
      - $BIND_MOUNTS/oxivia_mysql:/var/lib/mysql
    networks:
      - caddy
      - oxivia

networks:
  oxivia:
  caddy:
    external: true
    attachable: true
    driver: overlay
