services:
  djankiserv:
    image: marcpartensky/djankiserv
    restart: unless-stopped
    env_file: .env
    volumes:
    - /srv/djankiserv/static:/app/static
    - /srv/djankiserv/media:/app/media
    networks:
    - caddy
    - postgres
    labels:
      traefik.enable: 'true'
      traefik.http.services.djankiserv.loadbalancer.server.port: 8000
      traefik.http.routers.djankiserv.rule: 'Host(`djankiserv.marcpartensky.com`)

        '
      traefik.http.routers.djankiserv.entrypoints: web
networks:
  caddy:
    external: true
  postgres:
    external: true
