version: "3.9"
services:
  marc:
    image: marcpartensky/dotfiles
    build:
      context: /root/git/dotfiles
    networks:
      - box
    stdin_open: true
    tty: true

  samy:
    # image: marcpartensky/box
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - box

  etienne:
    # image: marcpartensky/box
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - box
    stdin_open: true
    tty: true

  valentin:
    # image: marcpartensky/box
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - box

  alexandre:
    # image: marcpartensky/box
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - box

networks:
  box:
