version: "3.9"
services:
  marc:
    image: marcpartensky/dotfiles
    build:
      context: /root/git/dotfiles
    networks:
      - box
    # stdin_open: true
    # tty: true

  samy:
    image: marcpartensky/box
    networks:
      - box

  etienne:
    image: marcpartensky/box
    networks:
      - box

  valentin:
    image: marcpartensky/box
    networks:
      - box

  alexandre:
    image: marcpartensky/box
    networks:
      - box

networks:
  box:
