version: "3.9"

services:
  valentin:
    image: marcpartensky/valentin-website
    restart: unless-stopped
    container_name: valentin
    environment:
      PRODUCTION: "False"
    networks:
      - caddy
    # labels:
    #   # caddy: valentin-colin.fr
    #   # caddy.reverse_proxy: "{{upstreams 80}}"
    #   traefik.enable: "true"
    #   traefik.http.routers.valentin.rule: Host(`valentin.marcpartensky.com`)
    #   traefik.http.routers.valentin.entrypoints: web
    #   # traefik.http.routers.valentin.tls.certresolver: tls
    #   traefik.http.services.valentin.loadbalancer.server.port: 80
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role == manager
    #   labels:
    #     traefik.enable: "true"
    #     traefik.http.routers.valentin.rule: Host(`valentin-colin.fr`)
    #     traefik.http.routers.valentin.entrypoints: websecure
    #     traefik.http.routers.valentin.tls.certresolver: tls
    #     traefik.http.services.valentin.loadbalancer.server.port: 80

networks:
  caddy:
    external: true
