services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    restart: unless-stopped
    env_file: .env
    volumes:
    - /srv/outline:/var/lib/outline/data
    networks:
    - postgres
    - redis
    - caddy
networks:
  redis:
    external: true
  postgres:
    external: true
  caddy:
    external: true
