version: "3.9"

services:
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      # - 80:80/tcp
      # - 443:443/tcp
      # - 443:443/udp
      # - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    networks:
      - caddy
    labels:
      caddy: adguardhome.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
      traefik.enable: "true"
      traefik.http.routers.adguardhome.rule: Host(`adguardhome.marcpartensky.com`)
      traefik.http.routers.adguardhome.entrypoints: websecure
      traefik.http.routers.adguardhome.tls.certresolver: tls
      traefik.http.services.adguardhome.loadbalancer.server.port: 3000
    volumes:
      - adguardhome_work:/opt/adguardhome/work
      - ../data/adguard:/opt/adguardhome/conf

volumes:
  adguardhome:

networks:
  caddy:
    external: true
