version: "3.9"
services:
  agenda_militant:
    image: marcpartensky/agenda-militant
    restart: unless-stopped
    networks:
      - caddy
    deploy:
      labels:
        caddy: agenda.militant.marcpartensky.com
        caddy.reverse_proxy: "{{upstreams 8080}}"
        traefik.enable: "true"
        traefik.http.routers.agenda_militant.rule: Host(`agenda.militant.marcpartensky.com`)
        traefik.http.routers.agenda_militant.entrypoints: websecure
        traefik.http.routers.agenda_militant.tls.certresolver: tls
        traefik.http.services.agenda_militant.loadbalancer.server.port: 8080
networks:
  caddy:
    external: true
