version: "3.9"
services:
  android:
    image: budtmo/docker-android-real-device
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
      - "4723:4723"
