version: "3.9"
services:
  android:
    image: budtmo/docker-android-x86-12.0
    restart: unless-stopped
    privileged: true
    # ports:
    #   - "6080:6080"
      - "5554:5554"
      - "5555:5555"
      - "4723:4723"
    environment:
      DEVICE: "Samsung Galaxy S6"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.android.rule: >
          Host(`android.marcpartensky.fr`)
        traefik.http.routers.android.entrypoints: websecure
        traefik.http.routers.android.tls.certresolver: cloudflare
        traefik.http.services.android.loadbalancer.server.port: 6080
