version: "3.9"
services:
  arch:
    image: marcpartensky/arch:vnc
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: arch.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      traefik.enable: "true"
      traefik.http.routers.arch.rule: Host(`arch.marcpartensky.com`)
      traefik.http.routers.arch.entrypoints: websecure
      traefik.http.routers.arch.tls.certresolver: tls
      traefik.http.services.arch.loadbalancer.server.port: 8080

networks:
  caddy:
    external: true
