version: "3.9"
services:
  arch:
    image: marcpartensky/arch:vnc
    restart: unless-stopped
    ports: # vnc is shared
      - "5900:5900"
    networks:
      - caddy
      - ldap
    volumes:
      - arch:/home/marc
    labels:
      caddy: arch.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      traefik.enable: "true"
      traefik.http.routers.arch.rule: Host(`arch.marcpartensky.com`)
      traefik.http.routers.arch.entrypoints: websecure
      traefik.http.routers.arch.tls.certresolver: tls
      traefik.http.services.arch.loadbalancer.server.port: 8080

volumes:
  arch:

networks:
  ldap:
    external: true
  caddy:
    external: true
