services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    container_name: calibre
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ../data/calibre/data:/config
      - /srv/calibre/books:/books
    # ports:
    #   - 8083:8083

networks:
  caddy:
    external: true
