version: "3.9"
services:
  cloudflare:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file: ../data/secrets/cloudflare.env
    command: tunnel --no-autoupdate run
    networks:
      - caddy

  traefik-cloudflare-tunnel:
    image: docker.io/justmiles/traefik-cloudflare-tunnel:latest
    restart: unless-stopped
    env_file:
      - ../data/secrets/cloudflare.env
    networks:
      - caddy

networks:
  caddy:
    external: true
