version: "3.9"
services:
  crontab:
    image: alseambusher/crontab-ui
    restart: unless-stopped
    networks:
      - caddy
    # ports:
    #   - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - crontabs:/crontab-ui/crontabs
    labels:
      traefik.enable: "true"
      traefik.http.services.crontab.loadbalancer.server.port: 8000
      traefik.http.routers.crontab.rule: >
        Host(`cron.marcpartensky.com`)
      traefik.http.routers.crontab.entrypoints: web
      # traefik.http.routers.ui.tls.certresolver: tls
      # traefik.http.routers.ui.tls.certresolver: cloudflare
      traefik.http.routers.crontab.middlewares: ldap_auth

volumes:
  crontabs:

networks:
  caddy:
    external: true
