version: "3.9"

services:
  bot:
    # image: docker.io/marcpartensky/discord-bot:v141.138ee20.2024-09-08
    image: docker.io/marcpartensky/discord-bot:latest
    # image: docker.io/marcpartensky/discord-bot:v152.04b7e7a.2024-09-15
    restart: unless-stopped
    ports:
      - "7010:8000"
    networks:
      - discord
      - postgres
    env_file:
      - ../data/secrets/discord-bot.env
    deploy:
      replicas: 1

  # ia:
  #   image: marcpartensky/discord-bot
  #   restart: unless-stkopped
  #   ports:
  #     - "7011:8000"
  #   networks:
  #     - discord
  #   env_file:
  #     - ../data/secrets/ia.env
  #   deploy:
  #     replicas: 1

  # chatgpt:
  #   image: xxxbrian/discord_chatgpt_bot:latest
  #   env_file:
  #     - ../data/secrets/discord_chatgpt.env

networks:
  discord:
  postgres:
    external: true
