version: "3.9"

services:
  discord_bot_mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - discord_bot_mongo:/data/db
    networks:
      - discord
    ports:
      - "27017:27017"
    env_file:
      - ../data/secrets/discord_bot_mongo.env
    # healthcheck:
    #   test: CMD echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

  mongo_express:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    env_file:
      - ../data/secrets/mongo_express.env
    networks:
      - discord
      - caddy
    depends_on:
      - discord_bot_mongo
    labels:
      caddy: mongo.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8081}}"
      traefik.enable: "true"
      traefik.http.routers.mongo.rule: Host(`mongo.marcpartensky.com`)
      traefik.http.routers.mongo.entrypoints: websecure
      traefik.http.routers.mongo.tls.certresolver: tls
      traefik.http.services.mongo.loadbalancer.server.port: 80

volumes:
  discord_bot_mongo:

networks:
  discord:
  caddy:
    external: true
    attachable: true
    driver: overlay
