version: "3.9"

services:
  docker_api:
    image: marcpartensky/docker-api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - discord

  # db:
  #   image: postgres
  #   container_name: docker-app-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: docker_user
  #     POSTGRES_PASSWORD: d3kTrklm54208
  #     POSTGRES_DB: docker
 
networks:
  discord:
