version: "3.9"

services:
  docker_api:
    image: marcpartensky/docker-api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - discord

networks:
  discord:
