version: "3.9"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      # CLI_ARGS:  #optional
    volumes:
      - /srv:/srv
      - duplicati_config:/config
      - duplicati_backups:/backups
      - duplicati_source:/source
    networks:
      - caddy
    labels:
      caddy: duplicati.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8200}}"
      traefik.enable: "true"
      traefik.http.services.duplicati.loadbalancer.server.port: 8200
      traefik.http.routers.duplicati.rule: >
        Host(`duplicati.marcpartensky.com`) || Host(`dupliati.marcpartensky.fr`)
      traefik.http.routers.duplicati.entrypoints: websecure
      # traefik.http.routers.duplicati.tls.certresolver: tls
      traefik.http.routers.duplicati.middlewares: ldap_auth
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.duplicati.loadbalancer.server.port: 8200
        # traefik.http.routers.duplicati.rule: Host(`duplicati.marcpartensky.com`)
        traefik.http.routers.duplicati.rule: >
          Host(`duplicati.marcpartensky.com`) || Host(`duplicati.marcpartensky.fr`)
        traefik.http.routers.duplicati.entrypoints: websecure
        # traefik.http.routers.duplicati.tls.certresolver: tls
        traefik.http.routers.duplicati.tls.certresolver: cloudflare
        # traefik.http.routers.duplicati.middlewares: ldap_auth

volumes:
  duplicati_config:
  duplicati_backups:
  duplicati_source:

networks:
  caddy:
    external: true
