version: "3.9"
services:
  etesync:
    image: victorrds/etesync
    restart: unless-stopped
    networks:
      - caddy
      - postgres
    env_file:
      - ../data/secrets/etesync.env
    volumes:
      - static:/srv/etebase/static
      - media:/data/media
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.etesync.loadbalancer.server.port: 3735
        traefik.http.routers.etesync.rule: >
          Host(`etesync.marcpartensky.com`) || Host(`etesync.marcpartensky.fr`)
        traefik.http.routers.etesync.entrypoints: websecure
        traefik.http.routers.etesync.tls.certresolver: tls
        # traefik.http.routers.etesync.tls.certresolver: cloudflare
        # traefik.http.routers.etesync.middlewares: ldap_auth

networks:
  postgres:
    external: true
  caddy:
    external: true

volumes:
  static:
  media:
