version: "3.9"

services:
  etherpad:
    image: etherpad/etherpad
    restart: unless-stopped
    environment:
      ADMIN_PASSWORD: supersecret
    networks:
        - caddy
    labels:
      caddy: etherpad.marcpartensky.com, pad.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 9001}}"
      traefik.enable: "true"
      traefik.http.routers.etherpad.rule: Host(`pad.marcpartensky.com`)
      traefik.http.routers.etherpad.entrypoints: websecure
      traefik.http.routers.etherpad.tls.certresolver: tls
      traefik.http.services.etherpad.loadbalancer.server.port: 9001
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.etherpad.rule: >
          Host(`pad.marcpartensky.com`) ||
          Host(`pad.marcpartensky.fr`)
        traefik.http.routers.etherpad.entrypoints: websecure
        traefik.http.routers.etherpad.tls.certresolver: tls
        traefik.http.services.etherpad.loadbalancer.server.port: 9001

networks:
  caddy:
    external: true
