version: "3.9"

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban:/data
      - /var/log:/var/log:ro
    env_file:
      - ../data/secrets/fail2ban.env

volumes:
  fail2ban:
