version: "3.9"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    # user: "${UID}:${GID}"
    user: "1000:100"
    # volumes:
    #   - /root/Videos:/data
    volumes:
      - /home/marc:/data
      - ../data/filebrowser:/config
    # environment:
      # FB_BASEURL: /filebrowser
    networks:
      - caddy
    labels:
      traefik.enable: "true"
      traefik.http.routers.filebrowser.rule: Host(`file.marcpartensky.com`)
      traefik.http.routers.filebrowser.entrypoints: web
      # traefik.http.routers.filebrowser.tls.certresolver: tls
      traefik.http.services.filebrowser.loadbalancer.server.port: 8080
      traefik.http.routers.filebrowser.middlewares: ldap_auth

networks:
  caddy:
    external: true

volumes:
  data:
