version: "3.9"
services:
  focalboard:
    image: mattermost/focalboard
    volumes:
      - data:/opt/focalboard/data
      - pack:/opt/focalboard/pack
      - ../data/focalboard/config.json:/opt/focalboard/config.json
    environment:
      EXCLUDE_ENTERPRISE: "1"
    networks:
      - postgres
    ports:
      - "8000:8000"

volumes:
  data:
  pack:
networks:
  postgres:
    external: true
