version: "3.9"
services:
  focalboard:
    image: mattermost/focalboard
    volumes:
      - focalboard:/opt/focalboard/data
    networks:
        - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.focalboard.rule: Host(`board.marcpartensky.com`)
        traefik.http.routers.focalboard.entrypoints: websecure
        traefik.http.routers.focalboard.tls.certresolver: tls
        traefik.http.services.focalboard.loadbalancer.server.port: 8008

volumes:
  focalboard:
networks:
  caddy:
    external: true
