version: "3.9"
services:
  focalboard:
    image: mattermost/focalboard
    volumes:
      - data:/opt/focalboard/data
      - pack:/opt/focalboard/pack
      - ../data/focalboard/config.json:/opt/focalboard/config.json
    environment:
      EXCLUDE_ENTERPRISE: "1"
    networks:
      - caddy
      - postgres
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.focalboard.rule: >
          Host(`board.marcpartensky.com`) || Host(`board.marcpartensky.fr`)
        traefik.http.routers.focalboard.entrypoints: websecure
        # traefik.http.routers.focalboard.tls.certresolver: tls
        traefik.http.services.focalboard.loadbalancer.server.port: 8000
        # traefik.http.routers.focalboard.middlewares: ldap_auth

volumes:
  data:
  pack:
networks:
  postgres:
    external: true
  caddy:
    external: true
