version: "3.9"
services:
  focalboard:
    image: mattermost/focalboard
    volumes:
      - data:/opt/focalboard/data
      - pack:/opt/focalboard/pack
      - ../data/focalboard/config.json:/opt/focalboard/config.json
    environment:
      EXCLUDE_ENTERPRISE: "1"
    networks:
      - caddy
      - postgres
    labels:
      traefik.enable: "true"
      traefik.http.routers.focalboard.rule: >
        Host(`board.tower.marcpartensky.com`)
      traefik.http.routers.focalboard.entrypoints: web
      # traefik.http.routers.focalboard.tls.certresolver: tls
      traefik.http.services.focalboard.loadbalancer.server.port: 8000
      # traefik.http.routers.focalboard.middlewares: ldap_auth

volumes:
  data:
  pack:
networks:
  postgres:
    external: true
  caddy:
    external: true
