version: "3.9"

services:
  gitea_postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ../data/secrets/gitea.env
    networks:
      - caddy
      - gitea
    volumes:
      - gitea_postgres:/var/lib/postgresql/data

networks:
  gitea:
