version: "3.9"

services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: unless-stopped
    hostname: gitlab.marcpartensky.com
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
    #     external_url 'http://gitlab.marcpartensky.com:8929'
    #     gitlab_rails['gitlab_shell_ssh_port'] = 2224
    # ports:
    #   - '8929:8929'
    #   - '2224:22'
    networks:
      - caddy
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    labels:
      caddy: gitlab.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams http 80}}"
      traefik.enable: "true"
      traefik.http.routers.gitlab.rule: Host(`gitlab.marcpartensky.com`)
      traefik.http.routers.gitlab.entrypoints: websecure
      traefik.http.routers.gitlab.tls.certresolver: tls
      traefik.http.services.gitlab.loadbalancer.server.port: 80

volumes:
  gitlab_config:
  gitlab_log:
  gitlab_data:

networks:
  caddy:
    external: true
