version: "3.9"
services:
  openvpn_client:
    image: qmcgaw/gluetun
  cap-add:
    - NET_ADMIN
  environment:
    # VPN_SERVICE_PROVIDER: protonvpn
    # VPN_SERVICE_PROVIDER: openvpn
    OPENVPN_USER: marcpartensky
    OPENVPN_PASSWORD: Lxxxxxxxxxyyyyyxxxxn
    # SERVER_COUNTRIES: France
    # FREE_ONLY: on # Only required when using ProtonVPN's free service
  ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp # Application container's ports to be published
  networks:
    - vpn

networks:
  vpn:
    external: true
