version: "3.9"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: France/Paris
    volumes:
      - ../data/heimdall:/config
    networks:
      - caddy
    labels:
      caddy: heimdall.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.heimdall.rule: Host(`heimdall.marcpartensky.com`)
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.routers.heimdall.tls.certresolver: tls
      traefik.http.services.heimdall.loadbalancer.server.port: 80

networks:
  caddy:
    external: true
