version: "3.9"
services:
  home-assistant:
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    # image: lscr.io/linuxserver/homeassistant:latest
    volumes:
      - /srv/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus:ro
    environment:
      TZ: Europe/Paris
    ports:
      - 8123:8123 #optional
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

