version: "3.9"

services:
  ia:
    image: marcpartensky/discord-bot
    restart: unless-stopped
    ports:
        - "7011:8000"
    networks:
      - discord
    depends_on:
      - docker_api
    env_file:
      - ../data/secrets/ia.env
    deploy:
      replicas: 1

networks:
  discord:
