version: "3.9"

services:
  ialab:
    image: marcpartensky/ialab:latest
    # volumes:
    #   - ialab:/app
    networks:
      - caddy
    labels:
      caddy: ialab.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      traefik.enable: "true"
      traefik.http.routers.ialab.rule: Host(`ialab.marcpartensky.com`)
      traefik.http.routers.ialab.entrypoints: websecure
      traefik.http.routers.ialab.tls.certresolver: tls
      traefik.http.services.ialab.loadbalancer.server.port: 80
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.ialab.rule: Host(`ialab.marcpartensky.com`)
        traefik.http.routers.ialab.entrypoints: websecure
        traefik.http.routers.ialab.tls.certresolver: tls
        traefik.http.services.ialab.loadbalancer.server.port: 80

# volumes:
#   ialab:
#
networks:
  caddy:
    external: true
