version: "3.9"

services:
  ialab:
    image: marcpartensky/ialab
    user: nobody
    restart: unless-stopped
    environment:
      FLASK_APP: server.py
    # env_file:
      # - $HOME/git/ialab/.flaskenv
    # working_dir: /app
    entrypoint: flask run --host ialab --port 80
    # entrypoint: "gunicorn server:app"
    # entrypoint: "gunicorn --chdir /app server:app"
    volumes:
      - ialab:/app
    networks:
      - caddy
    depends_on:
      - caddy
    labels:
      caddy: ialab.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.ialab.rule: Host(`ialab.marcpartensky.com`)
      traefik.http.routers.ialab.entrypoints: websecure
      traefik.http.routers.ialab.tls.certresolver: tls
      traefik.http.services.ialab.loadbalancer.server.port: 80

volumes:
  ialab:

networks:
  caddy:
    external: true
