version: "3.9"
services:
  image: hwdsl2/ipsec-vpn-server
  restart: unless-stopped
  privileged: true
  ports:
    - "500:500/udp"
    - "4500:4500/udp"
  volumes:
    - ikev2-vpn-data:/etc/ipsec.d
    - /lib/modules:/lib/modules:ro
