version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
    #   PUID: 1000
    #   PGID: 1000
    #   TZ: Europe/Paris
      JELLYFIN_PublishedServerUrl: jellyfin.marcpartensky.com
    devices:
      - /dev/dri
    volumes:
      - config:/config
      - cache:/cache
      - media:/media
      - movies:/movies
      - musics:/musics
      - photos:/photos
      - ~/Videos/Youtube:/videos
    # ports:
      # - 8920:8920 #optional https self signed
      # - 7359:7359/udp #optional lan discovery
      # - 1900:1900/udp #optional dnla
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
          # Host(`jellyfin.marcpartensky.fr`) ||
        traefik.http.routers.jellyfin.rule: >
          Host(`jellyfin.marcpartensky.com`)
        traefik.http.routers.jellyfin.entrypoints: web
          # traefik.http.routers.jellyfin.tls.certresolver: tls
        traefik.http.services.jellyfin.loadbalancer.server.port: 8096

volumes:
  config:
  cache:
  media:
  movies:
  musics:
  photos:
  videos:

networks:
  caddy:
    external: true
