version: "3.9"
services:
  jellyfin:
    restart: unless-stopped
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      # JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - library:/config
      - tvseries:/data/tvshows
      - movies:/data/movies
    # ports:
      # - 8920:8920 #optional https self signed
      # - 7359:7359/udp #optional lan discovery
      # - 1900:1900/udp #optional dnla
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.jellyfin.rule: Host(`jellyfin.marcpartensky.com`)
        traefik.http.routers.jellyfin.entrypoints: websecure
        traefik.http.routers.jellyfin.tls.certresolver: tls
        traefik.http.services.jellyfin.loadbalancer.server.port: 8096

volumes:
  library:
  tvseries:
  movies:

networks:
  caddy:
    external: true
