version: "3.9"
services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
    #   PUID: 1000
    #   PGID: 1000
    #   TZ: Europe/Paris
      JELLYFIN_PublishedServerUrl: jellyfin.marcpartensky.com
    devices:
      - /dev/dri
    volumes:
      - config:/config
      - cache:/cache
      - /srv/jellyfin/media:/media
      - /srv/jellyfin/movies:/movies
      - /srv/jellyfin/musics:/musics
      - /srv/jellyfin/photos:/photos
      - ~/Videos/Youtube:/videos
    # ports:
    #   - 8096:8096 #http
      # - 8920:8920 #optional https self signed
      # - 7359:7359/udp #optional lan discovery
      # - 1900:1900/udp #optional dnla
    networks:
      - caddy


volumes:
  config:
  cache:
  media:
  movies:
  musics:
  photos:
  videos:

networks:
  caddy:
    external: true
