version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy
    # ports:
    #   - "50000:50000"
    # labels:
    #   caddy: jenkins.marcpartensky.com
    #   caddy.reverse_proxy: "{{upstreams 8080}}"
    #   traefik.enable: "true"
    #   traefik.http.routers.jenkins.rule: Host(`jenkins.marcpartensky.com`)
    #   traefik.http.routers.jenkins.entrypoints: websecure
    #   traefik.http.routers.jenkins.tls.certresolver: tls
    #   traefik.http.services.jenkins.loadbalancer.server.port: 8080

volumes:
  jenkins:

networks:
  caddy:
    external: true
