version: "3.9"

services:
  jupyterhub:
    image: jupyterhub/jupyterhub
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - jupyterhub:/srv/jupyterhub
    networks:
    - caddy
    environment:
      DOCKER_JUPYTER_IMAGE: marcpartensky/jupyterlab
      DOCKER_NETWORK_NAME: jupyterhub
      HUB_IP: jupyterhub
    labels:
      caddy: jupyterhub.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      traefik.enable: "true"
      traefik.http.routers.jupyterhub.rule: Host(`jupyterhub.marcpartensky.com`)
      traefik.http.routers.jupyterhub.entrypoints: websecure
      traefik.http.routers.jupyterhub.tls.certresolver: tls
      traefik.http.services.jupyterhub.loadbalancer.server.port: 8000

networks:
  caddy:
    external: true
