version: "3.9"
services:
  ldap_manager_go:
    image: romnn/ldap-manager
    # command: --generate
    env_file:
     - ../data/secrets/ldap_manager_go.env
    networks:
     - ldap
     - caddy
    environment:
      HTTP_PORT: 80
      LDAP_HOST: "ldap"
      LDAP_PORT: 636
      # LDAP_ADMIN_PASSWORD: admin
      # LDAP_CONFIG_PASSWORD: config

      LDAP_ORGANIZATION: Marc Partensky
      LDAP_DOMAIN: marcpartensky.com
      DAP_BASE_DN: dc=admin,dc=org

      # DEFAULT_ADMIN_USERNAME: ldapadmin
      # DEFAULT_ADMIN_PASSWORD: changeme
      # FORCE_CREATE_ADMIN: "true"

      LDAP_TLS: "false"
      LDAP_USE_RFC2307BIS: "true"
      
      ISSUER: ldap@marcpartensky.com
      AUDIENCE: marcpartensky.com
      GENERATE: "true" # ports:
  #   - 9090:9090
    deploy:
      labels:
        traefik.enable: "true"
        # traefik.http.routers.ldap_manager_go.rule: Host(`ldapgo.marcpartensky.com`)
        traefik.http.routers.ldap_manager_go.rule: >
          Host(`ldapgo.marcpartensky.com`) || Host(`ldapgo.marcpartensky.fr`)
        traefik.http.routers.ldap_manager_go.entrypoints: websecure
        traefik.http.routers.ldap_manager_go.tls.certresolver: tls
        traefik.http.services.ldap_manager_go.loadbalancer.server.port: 80

networks:
  ldap:
    external: true
  caddy:
    external: true
