version: "3.9"

services:
  matrix:
    image: matrixdotorg/synapse
    restart: unless-stopped
    # environment:
    #   SYNAPSE_REPORT_STATS: "no"
    #   SYNAPSE_SERVER_NAME: matrix.marcpartensky.com
    #   SYNAPSE_ENABLE_REGISTRATION: "true"
    volumes:
      - ../data/matrix:/data
      # - matrix:/data
    networks:
        - caddy
    labels:
      caddy: matrix.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8008}}"
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: Host(`matrix.marcpartensky.com`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: tls
      traefik.http.services.nextcloud.loadbalancer.server.port: 8008

networks:
  caddy:
    external: true
