version: "3.9"

services:
  matrix:
    image: matrixdotorg/synapse
    restart: unless-stopped
    # environment:
    #   SYNAPSE_REPORT_STATS: "no"
    #   SYNAPSE_SERVER_NAME: matrix.marcpartensky.com
    #   SYNAPSE_ENABLE_REGISTRATION: "true"
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yml
    volumes:
      - ../data/matrix:/data
      # - matrix:/data
    networks:
      - caddy
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      caddy: matrix.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8008}}"
      traefik.enable: "true"
      traefik.http.routers.matrix.rule: Host(`matrix.marcpartensky.com`)
      traefik.http.routers.matrix.entrypoints: websecure
      traefik.http.routers.matrix.tls.certresolver: tls
      traefik.http.services.matrix.loadbalancer.server.port: 8008
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.matrix.rule: >
          Host(`matrix.marcpartensky.com`) || Host(`matrix.marcpartensky.fr`)
        traefik.http.routers.matrix.entrypoints: websecure
        traefik.http.routers.matrix.tls.certresolver: tls
        traefik.http.services.matrix.loadbalancer.server.port: 8008

networks:
  postgres:
    external: true
  caddy:
    external: true
