version: "3.9"

services:
  mcmyadmin:
    image: tekgator/docker-mcmyadmin:latest
    restart: unless-stopped
      # environment:
      #   PUID: 1001
      #   PGID: 1001
      #   EULA: 1
    volumes:
      - mcmyadmin:/data
    ports:
      - "25566:25565"
    networks:
      - minecraft
    labels:
      caddy: mcadmin.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      traefik.enable: "true"
      traefik.http.routers.minecraft.rule: Host(`mcadmin.marcpartensky.com`)
      traefik.http.routers.minecraft.entrypoints: websecure
      traefik.http.routers.minecraft.tls.certresolver: tls
      traefik.http.services.minecraft.loadbalancer.server.port: 8080

volumes:
  mcmyadmin:

networks:
  minecraft:
  caddy:
    external: true
