version: "3.9"

services:
  mcmyadmin:
    image: tekgator/docker-mcmyadmin:latest
    restart: unless-stopped
      # environment:
      #   PUID: 1001
      #   PGID: 1001
      #   EULA: 1
    volumes:
      - mcmyadmin:/data
    ports:
      - "25566:25565"
    networks:
      - minecraft
      - caddy
    labels:
      caddy: mcadmin.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      authorize.with: marc
      traefik.enable: "true"
      traefik.http.routers.mcmyadmin.rule: Host(`mcmyadmin.marcpartensky.com`)
      traefik.http.routers.mcmyadmin.entrypoints: websecure
      traefik.http.routers.mcmyadmin.tls.certresolver: tls
      traefik.http.services.mcmyadmin.loadbalancer.server.port: 8080
    deploy:
      labels:
        traefik.enable: "true"
        # traefik.http.routers.mcmyadmin.rule: Host(`mcmyadmin.marcpartensky.com`)
        traefik.http.routers.mcmyadmin.rule: Host(`mcmyadmin.marcpartensky.fr`)
        traefik.http.routers.mcmyadmin.entrypoints: websecure
        traefik.http.routers.mcmyadmin.tls.certresolver: tls
        traefik.http.services.mcmyadmin.loadbalancer.server.port: 8080

volumes:
  mcmyadmin:

networks:
  minecraft:
  caddy:
    external: true
