version: "3.9"

services:
  mcvnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    volumes:
      - /dev/shm:/dev/shm
      - mcvnc:/home/marc
      - mcvnc_usr:/usr
    ports:
      - 7900:5900
    environment:
      USER: marc
      PASSWORD: test
    networks:
      - minecraft
      - caddy
    depends_on:
      - minecraft
    labels:
      caddy: minecraft.marcpartensky.com, mc.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.gitea.rule: Host(`mc.marcpartensky.com`)
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.tls.certresolver: tls
      traefik.http.services.gitea.loadbalancer.server.port: 80

volumes:
  mcvnc:
  mcvnc_usr:

networks:
  minecraft:
  caddy:
    external: true
