version: "3.9"

services:
  server:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      EULA: "TRUE"
      OPS: MazexRedstone
      ENABLE_COMMAND_BLOCK: "TRUE"
      MEMORY: 2G
      VERSION: 1.16.5
      ICON: https://cdn.discordapp.com/attachments/507519157387132940/998015338966945822/unknown.png
      MOTD: Made in Marc Partensky
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      LEVEL: Server
      ONLINE_MODE: "FALSE" # no need for an account
      DIFFICULTY: hard
      VIEW_DISTANCE: 32
      # MAX_PLAYERS: 50
      # WORLD: $BIND_MOUNTS/minecraft/zip/Server.zip
      # SNOOPER_ENABLED: false
    volumes:
      - /srv/minecraft/champi:/data
      # - minecraft:/data
    ports:
      - "25565:25565"
    networks:
      - minecraft

  backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "1d"
      # instead of network_mode below, could declare RCON_HOST
      SERVE_PORT: 25565
      RCON_HOST: server
      RCON_PORT: 25575
      PAUSE_IF_NO_PLAYER: "true"
      PLAYERS_ONLINE_CHECK_INTERVAL: 1h
      TZ: Europe/Paris
      DEST_DIR: /backups
    networks:
      - minecraft
    volumes:
    # mount the same volume used by server, but read-only
    - /srv/minecraft/champi:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - /srv/mcbackups:/backups
    # share network namespace with server to simplify rcon access
    # network_mode: "service:mc"

# volumes:
#   minecraft:

networks:
  minecraft:
