version: "3.9"

services:
  minecraft_champi:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      EULA: "TRUE"
      OPS: MazexRedstone
      ENABLE_COMMAND_BLOCK: "TRUE"
      MEMORY: 2G
      VERSION: 1.16.5
      ICON: https://cdn.discordapp.com/attachments/507519157387132940/998015338966945822/unknown.png
      MOTD: Made in Marc Partensky
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      LEVEL: Server
      ONLINE_MODE: "FALSE" # no need for an account
      DIFFICULTY: hard
      VIEW_DISTANCE: 32
      # MAX_PLAYERS: 50
      # WORLD: $BIND_MOUNTS/minecraft/zip/Server.zip
      # SNOOPER_ENABLED: false
    volumes:
      - /srv/minecraft/champi:/data
      # - minecraft:/data
    ports:
      - "25565:25565"
    networks:
      - minecraft

# volumes:
#   minecraft:

networks:
  minecraft:
