version: "3.9"
services:
  minio:
    image: docker.io/minio/minio
    restart: unless-stopped
    networks:
      - caddy
      # - ldap
    volumes:
      - /srv/minio:/data
    env_file:
      - ../data/secrets/minio.env
    command: server /data --console-address ":9001"
    # healthcheck:
    #   test: ["CMD", "mc", "ready", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    labels:
      traefik.enable: true
      traefik.http.routers.minio.rule: Host(`storage.marcpartensky.com`)
      traefik.http.routers.minio.entrypoints: web
      traefik.http.services.minio.loadbalancer.server.port: 9001
networks:
  # ldap:
  #   external: true
  caddy:
    external: true
