version: "3.9"

services:
  miner:
    image: giansalex/monero-miner
    restart: unless-stopped
    env_file:
     - ../data/secrets/monero_miner.env
    # entrypoint: /xmr/xmrig \
    #   -o pool.supportxmr.com:3333 \
    #   -u $WALLET \
    #   -k  \
    #   --cpu-priority=2
    deploy:
      resources:
        reservations:
            cpus: "4"
            # memory: "512M"
            memory: "5G"

