version: "3.9"

services:
  mongo_express:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    env_file:
      - ../data/secrets/mongo_express.env
    networks:
      - discord
      - caddy
    depends_on:
      - discord_bot_mongo
    labels:
      caddy: mongo.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8081}}"
      traefik.enable: "true"
      traefik.http.routers.mongo.rule: Host(`mongo.marcpartensky.com`)
      traefik.http.routers.mongo.entrypoints: websecure
      traefik.http.routers.mongo.tls.certresolver: tls
      traefik.http.services.mongo.loadbalancer.server.port: 80

networks:
  discord:
  caddy:
    external: true
    attachable: true
    driver: overlay
