version: "3.9"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ../data/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../data/mongo/config:/etc/mongo
      - /srv/mongo:/data/db
    networks:
      - mongo
    ports:
      - "27017:27017"
    env_file:
      - ../data/secrets/mongo.env
    # healthcheck:
    #   test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
    # healthcheck:
    #   test: ["CMD", "echo",  "'db.runCommand("ping").ok'", ""| mongo localhost:27017/test --quiet
    # healthcheck:
    #   test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

  express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    env_file:
      - ../data/secrets/mongo_express.env
    networks:
      - mongo
      - caddy
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "--spider", "127.0.0.1:8081/status"]
    # labels:
    #   # caddy: mongo.marcpartensky.com, mongo.marc.wf, mongo.marc.tf
    #   # caddy.reverse_proxy: "{{upstreams 8081}}"
    #   traefik.enable: "true"
    #   traefik.http.routers.mongo.rule: Host(`mongo.marcpartensky.com`)
    #     # traefik.http.routers.mongo.entrypoints: websecure
    #   traefik.http.routers.mongo.entrypoints: web
    #     # traefik.http.routers.mongo.tls.certresolver: tls
    #   traefik.http.services.mongo.loadbalancer.server.port: 8081
    #    # traefik.http.routers.duplicati.middlewares: ldap_auth
    # deploy:
    #   labels:
    #     traefik.enable: "true"
    #     # traefik.http.routers.mongo.rule: Host(`mongo.marcpartensky.com`)
    #     traefik.http.routers.mongo.rule: >
    #       Host(`mongo.marcpartensky.fr`) ||
    #       Host(`mongo.marcpartensky.com`)
    #     traefik.http.routers.mongo.entrypoints: websecure
    #     traefik.http.routers.mongo.tls.certresolver: tls
    #     traefik.http.services.mongo.loadbalancer.server.port: 8081
    #     traefik.http.routers.mongo.middlewares: ldap_auth

volumes:
  mongo:

networks:
  mongo:
    external: true
  caddy:
    external: true
    attachable: true
    driver: overlay
