version: "3.9"

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      # - nextcloud:/var/www/html/data
      # - nextcloud_theme:/var/www/html/themes/<YOUR_CUSTOM_THEME>
      # - nextcloud_apps:/var/www/html/custom_apps
      # - nextcloud_config:/var/www/html/config
    env_file:
      - ../data/secrets/nextcloud.env
    networks:
      - caddy
      - nextcloud
        # depends_on:
        #   - nextcloud_mariadb
    labels:
      caddy: cloud.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams http 80}}"
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: Host(`cloud.marcpartensky.com`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: tls
      traefik.http.services.nextcloud.loadbalancer.server.port: 80

volumes:
  nextcloud:

networks:
  nextcloud:
  caddy:
    external: true
