version: "3.9"

services:
  nextcloud:
    image: docker.io/nextcloud
    restart: unless-stopped
    # user: "1000:100"
    volumes:
      # - nextcloud:/var/www/html
      - ../data/nextcloud/config:/var/www/html/config
      - /srv/nextcloud/data:/var/www/html/data
      - /srv/nextcloud/themes:/var/www/html/themes
      - /srv/nextcloud/apps:/var/www/html/custom_apps
      - ../data/nextcloud/test:/test

    env_file:
      - ../data/secrets/nextcloud.env
    networks:
      - caddy
      - postgres
      - redis
      - ldap
        # depends_on:
        #   - nextcloud_mariadb
    labels:
      caddy: cloud.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams http 80}}"
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: >
        Host(`cloud.marcpartensky.com`)
      traefik.http.routers.nextcloud.entrypoints: web
      # traefik.http.routers.nextcloud.tls.certresolver: tls
      traefik.http.services.nextcloud.loadbalancer.server.port: 80

volumes:
  data:
  config:
  themes:
  apps:

networks:
  ldap:
    external: true
  caddy:
    external: true
  postgres:
    external: true
  redis:
    external: true
