version: "3.9"

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    volumes:
      # - nextcloud:/var/www/html
      - data:/var/www/html/data
      - config:/var/www/html/config
      - themes:/var/www/html/themes
      - apps:/var/www/html/custom_apps
    env_file:
      - ../data/secrets/nextcloud.env
    networks:
      - caddy
      - postgres
      - nextcloud
        # depends_on:
        #   - nextcloud_mariadb
    labels:
      caddy: cloud.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams http 80}}"
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: Host(`cloud.marcpartensky.com`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: tls
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.nextcloud.rule: Host(`cloud.marcpartensky.com`)
        traefik.http.routers.nextcloud.entrypoints: websecure
        traefik.http.routers.nextcloud.tls.certresolver: tls
        traefik.http.services.nextcloud.loadbalancer.server.port: 80

volumes:
  data:
  config:
  themes:
  apps:

networks:
  nextcloud:
  caddy:
    external: true
  postgres:
    external: true
