services:
  nocodb:
    image: nocodb/nocodb:latest
    volumes:
      - /srv/nocodb:/usr/app/data
    env_file:
      - ../data/secrets/nocodb.env
    networks:
      - postgres
      - caddy
    labels:
      traefik.enable: "true"
      traefik.http.services.nocodb.loadbalancer.server.port: 8080
      traefik.http.routers.nocodb.rule: >
        Host(`noco.marcpartensky.com`)
      traefik.http.routers.nocodb.entrypoints: web
      # traefik.http.routers.nocodb.middlewares: ldap_auth
    healthcheck:
      test: curl http://localhost:8080/api/v1/health

networks:
  caddy:
    external: true
  postgres:
    external: true
