version: "3.9"
services:

  numeris_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    links:
      - numeris_mysql:db
    networks:
      - caddy
      - numeris_mysql
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.numeris_phpmyadmin.rule: Host(`phpmyadmin.numeris.marcpartensky.com`)
        traefik.http.routers.numeris_phpmyadmin.entrypoints: websecure
        traefik.http.routers.numeris_phpmyadmin.tls.certresolver: tls
        traefik.http.services.numeris_phpmyadmin.loadbalancer.server.port: 80
        traefik.http.routers.numeris_phpmyadmin.middlewares: ldap_auth

  numeris_mysql:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - numeris_mysql
    volumes:
    - numeris_mysql:/var/lib/mysql
    env_file:
      - ../data/secrets/numeris.env

  numeris_back:
    image: numerisisep/numeris-back
    networks:
      - caddy
      - numeris_mysql
    env_file:
      - ../data/secrets/numeris.env
    # volumes:
    #   - .env:/home/numeris/.env
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.numeris_back.rule: Host(`api.numeris.marcpartensky.com`)
        traefik.http.routers.numeris_back.entrypoints: websecure
        traefik.http.routers.numeris_back.tls.certresolver: tls
        traefik.http.services.numeris_back.loadbalancer.server.port: 80

  numeris_front:
    image: numerisisep/numeris-front
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.numeris_front.rule: Host(`numeris.marcpartensky.com`)
        traefik.http.routers.numeris_front.entrypoints: websecure
        traefik.http.routers.numeris_front.tls.certresolver: tls
        traefik.http.services.numeris_front.loadbalancer.server.port: 80
        traefik.http.routers.numeris_front.middlewares: ldap_auth

networks:
  numeris_mysql:
  caddy:
    external: true

volumes:
  numeris_mysql:
  caddy_data:
  mysql:
