version: "3.9"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    env_file:
      - ../data/secrets/numeris.env
    links:
      - numeris_mysql:db
    networks:
      - caddy
      - numeris_mysql
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.phpmyadmin.rule: Host(`phpmyadmin.numeris.marcpartensky.com`)
        traefik.http.routers.phpmyadmin.entrypoints: websecure
        traefik.http.routers.phpmyadmin.tls.certresolver: tls
        traefik.http.services.phpmyadmin.loadbalancer.server.port: 80
        traefik.http.routers.phpmyadmin.middlewares: ldap_auth

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - numeris_mysql
    volumes:
    - numeris_mysql:/var/lib/mysql
    env_file:
      - ../data/secrets/numeris.env

  back:
    image: numerisisep/numeris-back:prod
    networks:
      - caddy
      - numeris_mysql
    env_file:
      - ../data/secrets/numeris.env
    # volumes:
    #   - .env:/home/numeris/.env
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.back.rule: Host(`api.numeris.marcpartensky.com`)
        traefik.http.routers.back.entrypoints: websecure
        traefik.http.routers.back.tls.certresolver: tls
        traefik.http.services.back.loadbalancer.server.port: 80

  front:
    image: numerisisep/numeris-front:prod
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.front.rule: Host(`numeris.marcpartensky.com`)
        traefik.http.routers.front.entrypoints: websecure
        traefik.http.routers.front.tls.certresolver: tls
        traefik.http.services.front.loadbalancer.server.port: 80
        traefik.http.routers.front.middlewares: ldap_auth

networks:
  numeris_mysql:
  caddy:
    external: true

volumes:
  numeris_mysql:
  caddy_data:
  mysql:
