version: "3.9"

services:
  ocis:
    image: owncloud/ocis:latest
    environment:
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "true"

      # OCIS_URL: the external domain / ip address of oCIS (with protocol, must always be https)
      # OCIS_URL: "https://0.0.0.0:9200"
      OCIS_URL: "https://ocis.marcpartensky.com"

      # OCIS_LOG_LEVEL: error / info / ... / debug
      OCIS_LOG_LEVEL: info
    ports:
      - "9200:9200"
      - "9140:9140"
    networks:
    - caddy
    - ldap
    # volumes:
    #   # mount the ocis config file inside the container
    #   - "../data/ocis:/etc/ocis/"
    env_file:
      - "../data/secrets/ocis.env"
    labels:
      traefik.enable: "true"
      traefik.http.services.ocis.loadbalancer.server.scheme: https
      traefik.http.services.ocis.loadbalancer.server.port: 9200
      traefik.http.routers.ocis.rule: >
        Host(`ocis.marcpartensky.com`)
      traefik.http.routers.ocis.entrypoints: web
      # traefik.http.routers.ocis.middlewares: ldap_auth

networks:
  ldap:
    external: true
  caddy:
    external: true
