services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: unless-stopped
    env_file: ../data/secrets/outline.env
    volumes:
      - /srv/outline:/var/lib/outline/data
    networks:
      - postgres
      - redis
      - caddy
    labels:
      traefik.enable: "true"
      traefik.http.services.outline.loadbalancer.server.port: 3000
      traefik.http.routers.outline.rule: >
        Host(`outline.marcpartensky.com`)
      traefik.http.routers.outline.entrypoints: web
      # traefik.http.routers.outline.middlewares: ldap_auth


  # https-portal:
  #   image: steveltn/https-portal
  #   env_file: ./docker.env
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     - outline
  #   restart: always
  #   volumes:
  #     - https-portal-data:/var/lib/https-portal
  #   healthcheck:
  #     test: ["CMD", "service", "nginx", "status"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   environment:
  #     DOMAINS: 'docs.mycompany.com -> http://outline:3000'
  #     STAGE: 'production'
  #     WEBSOCKET: 'true'
  #     CLIENT_MAX_BODY_SIZE: '0'

networks:
  redis:
    external: true
  postgres:
    external: true
  caddy:
    external: true
