version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - ../data/secrets/pgadmin.env
    environment:
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      # PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    networks:
      - postgres
      - caddy
    volumes:
      - /srv/pgadmin:/usr/local/
    labels:
      caddy: pgadmin.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      # caddy.reverse_proxy.header_up.Host: "{upstream_hostport}" # redundant
      # caddy.reverse_proxy.header_up.X-Real-IP: "{host}"
      # caddy.reverse_proxy.header_up.X-Forwarded-For: "{host}"  # redundant
      # caddy.basicauth: /* bcrypt
      # caddy.basicauth.admin: JDJhJDEyJDVRUXdqQllCR2dCSEZ0ZUlaVUZTRE95WXpROFdUcFdXSm4wVGE2TmE4cEkxNHc5Si4venJxCg==
      traefik.enable: "true"
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.marcpartensky.com`)
      traefik.http.routers.pgadmin.entrypoints: websecure
      traefik.http.routers.pgadmin.tls.certresolver: tls
      traefik.http.services.pgadmin.loadbalancer.server.port: 80

volumes:
  postgres:

networks:
  postgres:
    external: true
  caddy:
    external: true
