version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: docker.marcpartensky.com
      VIRTUAL_PORT: 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - caddy
    command:
      - --logo
      - https://marcpartensky.com/static/home/assets/img/white-orchid.svg
        # healthcheck:
        # test: ["CMD", "curl", "-f", "http://localhost:9000"]
        # test: ["CMD", "portainer", "--healthcheck"]
    depends_on:
      - caddy
    labels:
      caddy: docker.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 9000}}"
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: Host(`docker.marcpartensky.com`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls.certresolver: tls
      traefik.http.services.portainer.loadbalancer.server.port: 9000

volumes:
  portainer:

networks:
  caddy:
    external: true
