version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    # user: postgres:postgres
    # user: "974:974"
    ports:
      - target: 5432
        published: 5432
        mode: host
    volumes:
      - ../data/postgres:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
      - ../data/postgres/server.crt:/var/lib/postgresql/server.crt
      - ../data/postgres/server.key:/var/lib/postgresql/server.key
    env_file:
      - ../data/secrets/postgres.env
    command: |
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    networks:
      - postgres


volumes:
  postgres:

networks:
  postgres:
    external: true
