version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ../data/postgres:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    env_file:
      - ../data/secrets/postgres.env
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    external: true
  caddy:
    external: true
