version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ../data/postgres:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ../data/secrets/postgres.env
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"] # log level verbose
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    external: true
