version: "3.9"

services:
  pritunl:
    image: goofball222/pritunl
    restart: unless-stopped
    ports:
      - "1194-1195:1194-1195/udp"
    # depends_on:
    #     - pritunl_mongo
    environment:
      REVERSE_PROXY: "true"
      TZ: Europe/Paris
      MONGODB_URI: mongodb://mongo:27017/pritunl
      PRITUNL_DEBUG: "true"
      # WIREGUARD: true
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      # healthcheck:
      #   test: ["CMD", "wget", "-q", "localhost:80", "-O", "/dev/null"]
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    networks:
      - mongo
      - caddy
      - pritunl
    deploy:
      labels:
        caddy: vpn.marcpartensky.com
        caddy.reverse_proxy: "{{upstreams http 9700}}"
        traefik.enable: "true"
        traefik.http.routers.pritunl.rule: >
          Host(`vpn.marcpartensky.fr`) ||
          Host(`vpn.marcpartensky.com`)
        traefik.http.routers.pritunl.entrypoints: websecure
        traefik.http.routers.pritunl.tls.certresolver: tls
        traefik.http.services.pritunl.loadbalancer.server.port: 9700

networks:
  caddy:
    external: true
  mongo:
    external: true
  pritunl:
    external: true
    # internal: true
    # driver: bridge
    # ipam:
    #   config:
        # - subnet: 172.177.0.0/16
        # - subnet: 10.177.0.0/16
