version: '3.8'
x-common:
  panel:
    &panel-environment
    APP_URL: "https://pterodactyl.marcpartensky.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@pterodactyl.marcpartensky.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@pterodactyl.marcpartensky.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  pterodactyl_panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    links:
      - pterodactyl_mariadb
      - pterodactyl_redis
    volumes:
      - pterodactyl_panel_var:/app/var/
      - pterodactyl_panel_logs:/app/storage/logs
      - pterodactyl_nginx/:/etc/nginx/http.d
      - pterodactyl_certs/:/etc/letsencrypt
    env_file:
      - ../data/secrets/pterodactyl.env
    environment:
      <<: [*panel-environment, *mail-environment]
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: pterodactyl_redis
      DB_HOST: pterodactyl_mariadb
      DB_PORT: 3306
      DB_USERNAME: pterodactyl
    networks:
      - pterodactyl
      - caddy
    labels:
      caddy: pterodactyl.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      traefik.enable: "true"
      traefik.http.routers.pterodactyl.rule: Host(`pterodactyl.marcpartensky.com`)
      traefik.http.routers.pterodactyl.entrypoints: websecure
      traefik.http.routers.pterodactyl.tls.certresolver: tls
      traefik.http.services.pterodactyl.loadbalancer.server.port: 80

  pterodactyl_mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - pterodactyl_mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    env_file:
      - ../data/secrets/pterodactyl.env
    networks:
      - pterodactyl

  pterodactyl_redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - pterodactyl

  pterodactyl_wing_1:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
      - pterodactyl
    ports:
      - "8080:8080"
      - "2022:2022"
      - "443:443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - pterodactyl_etc:/etc/pterodactyl
      - pterodactyl_var_lib:/var/lib/pterodactyl
      - pterodactyl_var_log:/var/log/pterodactyl
      - /tmp/pterodactyl:/tmp/pterodactyl
      # - /etc/ssl/certs:/etc/ssl/certs:ro
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
    labels:
      caddy: wing1.pterodactylmarcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      traefik.enable: "true"
      traefik.http.routers.pterodactyl_wing_1.rule: Host(`wing1.pterodactyl.marcpartensky.com`)
      traefik.http.routers.pterodactyl_wing_1.entrypoints: websecure
      traefik.http.routers.pterodactyl_wing_1.tls.certresolver: tls
      traefik.http.services.pterodactyl_wing_1.loadbalancer.server.port: 8080


volumes:
  pterodactyl_mariadb:
  pterodactyl_panel_var:
  pterodactyl_panel_logs:

networks:
  pterodactyl:
  caddy:
    external: true
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
