version: '3.8'
x-common:
  panel:
    &panel-environment
    APP_URL: "https://pterodactyl.marcpartensky.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@pterodactyl.marcpartensky.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@pterodactyl.marcpartensky.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  pterodactyl_mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - pterodactyl_mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    env_file:
      - ../data/secrets/pterodactyl.env

  pterodactyl_redis:
    image: redis:alpine
    restart: unless-stopped

  pterodactyl_panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - pterodactyl_mariadb
      - pterodactyl_redis
    volumes:
      - pterodactyl_panel_var/:/app/var/
      - pterodactyl_panel_logs/:/app/storage/logs
    env_file:
      - ../data/secrets/pterodactyl.env
    environment:
      <<: [*panel-environment, *mail-environment]
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      DB_USERNAME: "pterodactyl"
    networks:
      - pterodactyl
      - caddy
    labels:
      caddy: pterodactyl.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  pterodactyl_mariadb:
  pterodactyl_panel_var:
  pterodactyl_panel_logs:

networks:
  pterodactyl:
  caddy:
    external: true
