version: "3.9"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      MENU_VERSION: 1.9.9 #optional
      PORT_RANGE: 30000:30010 #optional
      SUBFOLDER: / #optional
    volumes:
      - ../data/pxe/config:/config
      - ../data/pxe/assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
