version: "3.9"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ../data/qbittorrent:/config
      - /srv/jellyfin/Videos:/downloads
    networks:
      - caddy
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.services.qbittorrent.loadbalancer.server.port: 7681
    #   traefik.http.routers.qbittorrent.rule: >
    #     Host(`qbittorrent.marcpartensky.com`)
    #   traefik.http.routers.qbittorrent.entrypoints: web
    #   traefik.http.routers.qbittorrent.tls.certresolver: tls
    #   traefik.http.routers.qbittorrent.middlewares: ldap_auth
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
networks:
  caddy:
    external: true
