version: "3.9"

services:
  rancher:
    image: rancher/rancher:stable
    container_name: rancher
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/rancher:/var/lib/rancher
    networks:
      - caddy
    privileged: true
    user: root
    environment:
      CATTLE_SYSTEM_CATALOG: bundled
    # labels:
    #   caddy: rancher.marcpartensky.com
    #   caddy.reverse_proxy: "{{upstreams 8080}}"
    #   traefik.enable: "true"
    #   traefik.http.routers.rancher.rule: Host(`rancher.marcpartensky.com`)
    #   traefik.http.routers.rancher.entrypoints: web
    #     # traefik.http.routers.rancher.tls.certresolver: tls
    #   traefik.http.services.rancher.loadbalancer.server.port: 80
        # user: root
        # deploy:
        #   resources:
        #     limits:
        #       cpus: '4'
        #       memory: 5000M

networks:
  caddy:
    external: true
