version: "3.9"

services:
  rancher:
    image: rancher/server
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - caddy
    labels:
      caddy: rancher.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: Host(`rancher.marcpartensky.com`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: tls
      traefik.http.services.nextcloud.loadbalancer.server.port: 8080
    user: root
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 5000M

networks:
  caddy:
    external: true
