version: "3.9"
services:
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - redis

networks:
  redis:
    external: true
