version: "3.9"
services:
  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - ../data/redis:/usr/local/etc/redis
      - /srv/redis:/data
    healthcheck:
       test: ["CMD", "redis-cli","ping"]
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role == manager

networks:
  redis:
    external: true
