version: "3.9"

services:
  server:
    image: amruthpillai/reactive-resume:server-latest
    restart: unless-stopped
    env_file:
      - ../data/secrets/resume.env
    networks:
      - caddy
      - postgres
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.server.loadbalancer.server.port: 3100
        # traefik.http.routers.server.rule: Host(`api.cv.marcpartensky.fr`)
        traefik.http.routers.server.rule: Host(`api.cv.marcpartensky.fr`)
        # traefik.http.routers.server.rule: >
        #   Host(`server.marcpartensky.com`) || Host(`server.marcpartensky.fr`)
        traefik.http.routers.server.entrypoints: websecure
        traefik.http.routers.server.tls.certresolver: cloudflare
        traefik.http.routers.server.middlewares: ldap_auth

  client:
    image: amruthpillai/reactive-resume:client-latest
    restart: unless-stopped
    env_file:
     - ../data/secrets/resume.env
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.client.loadbalancer.server.port: 3000
        traefik.http.routers.client.rule: Host(`cv.marcpartensky.fr`)
        # traefik.http.routers.client.rule: >
        #   Host(`client.marcpartensky.com`) || Host(`client.marcpartensky.fr`)
        traefik.http.routers.client.entrypoints: websecure
        traefik.http.routers.client.tls.certresolver: cloudflare
        traefik.http.routers.client.middlewares: ldap_auth
networks:
  postgres:
    external: true
  caddy:
    external: true

