version: "3.9"

services:
  resume:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    env_file:
      - ../data/secrets/resume.env
        # environment:
        #   PUBLIC_URL: https://cv.marcpartensky.com
    networks:
      - postgres
      - redis
    ports:
      - 8002:3000

  printer:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: unless-stopped
    env_file:
      - ../data/secrets/resume.env
    ports:
      - 8003:3000
    environment:
        #   TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

networks:
  postgres:
    external: true
  caddy:
    external: true
  redis:
    external: true
