version: "3.9"

services:
  rustdesk_hbbs:
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    command: hbbs -r example.com:21117
    volumes:
      - rustdesk_hbbs:/root
    networks:
      - rustdesk
    depends_on:
      - rustdesk_hbbr

  rustdesk_hbbr:
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    ports:
      - 21117:21117
      - 21119:21119
    command: hbbr
    volumes:
      - rustdesk_hbbr:/root
    networks:
      - rustdesk

volumes:
  rustdesk_hbbs:
  rustdesk_hbbr:

networks:
  rustdesk:
