version: "3.9"
services:
  satisfactory-server:
    image: "wolveix/satisfactory-server:latest"
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
      - "15000:15000/udp"
      - "15777:15777/udp"
    environment:
      PUID: 1000
      PGID: 1000
      AUTOSAVEINTERVAL: 300
      AUTOSAVENUM: 5
      MAXPLAYERS: 4
      #- DISABLESEASONALEVENTS=true
    volumes:
      - './config:/config'
