version: "3.9"
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_dev  # Requested, set the root's password of MySQL service.
      MYSQL_LOG_CONSOLE: true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: seafile-elasticsearch
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - /opt/seafile-elasticsearch/data:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile-net

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    ports:
      # - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      DB_HOST: db
      DB_ROOT_PASSWD: db_dev  # Requested, the value should be root's password of MySQL service.
      TIME_ZONE: Europe/Paris # Optional, default is UTC. Should be uncomment and set to your local time zone.
      SEAFILE_ADMIN_EMAIL: marc@marcpartensky.com
      SEAFILE_ADMIN_PASSWORD: asecret     # Specifies Seafile admin password, default is 'asecret'
      SEAFILE_SERVER_LETSENCRYPT: false   # Whether to use https or not
      SEAFILE_SERVER_HOSTNAME: seafile.marcpartensky.com # Specifies your host name if https is enabled
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - seafile-net
      - caddy
    labels:
      caddy: seafile.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  seafile-net:
  caddy:
    external: true
