version: "3.9"

services:
  seafile_mariadb:
    image: mariadb:10.5
    env_file:
      - ../data/secrets/seafile.env
    volumes:
      - seafile_mysql:/var/lib/mysql
    networks:
      - seafile

  seafile_memcached:
    image: memcached:1.5.6
    entrypoint: memcached -m 256
    networks:
      - seafile

  seafile:
    image: seafileltd/seafile-mc:latest
    volumes:
      - seafile:/shared
    env_file:
      - ../data/secrets/seafile.env
    depends_on:
      - seafile_mariadb
      - seafile_memcached
    networks:
      - seafile
      - caddy
    labels:
      caddy: seafile.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams http 80}}"
      traefik.enable: "true"
      traefik.http.routers.seafile.rule: Host(`seafile.marcpartensky.com`)
      traefik.http.routers.seafile.entrypoints: websecure
      traefik.http.routers.seafile.tls.certresolver: tls
      traefik.http.services.seafile.loadbalancer.server.port: 80

volumes:
  seafile:
  seafile_mysql:

networks:
  seafile:
  caddy:
    external: true
