version: "3.9"
services:
  db:
    image: mariadb:10.5
    container_name: seafile_mariadb
    restart: unless-stopped
    env_file:
      - ../data/secrets/seafile.env
    volumes:
      - seafile_mariadb:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: seafile-elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 2g
    volumes:
      - seafile_elasticsearch:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    restart: unless-stopped
    # ports:
      # - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    # environment:
    #   SEAFILE_BOOTSTRAP: true
    volumes:
      - /srv/seafile:/shared/seafile
      # - seafile:/shared/seafile/seafile-data
      # - seahub:/shared/seafile/seahub-data
      # - ../data/seafile:/shared/seafile/conf
      # - ../data/seafile/ccnet.conf:/shared/seafile/conf/ccnet.conf
      # - ../data/seafile/gunicorn.conf.py:/opt/seafile/conf/gunicorn.conf.py
      # - ../data/seafile/seafdav.conf:/opt/seafile/conf/seafdav.conf
      # - ../data/seafile/seafevents.conf:/opt/seafile/conf/seafevents.conf
      # - ../data/seafile/seafile.conf:/opt/seafile/conf/seafile.conf
      # - ../data/seafile/seahub_settings.py:/opt/seafile/conf/seahub_settings.py
    env_file:
      - ../data/secrets/seafile.env
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - seafile
      - caddy
    labels:
      caddy: seafile.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  seafile:
  seahub:
  seafile_mariadb:
  seafile_elasticsearch:

networks:
  seafile:
  caddy:
    external: true
