version: "3.9"
services:
  db:
    image: mariadb:10.5
    container_name: seafile_mariadb
    restart: unless-stopped
    env_file:
      - ../data/secrets/seafile.env
    volumes:
      - seafile_mariadb:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: seafile-elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - seafile_elasticsearch:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    restart: unless-stopped
    # ports:
      # - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - seafile:/shared   # Requested, specifies the path to Seafile data persistent store.
      # - ../data/seafile:/opt/seafile/conf
    env_file:
      - ../data/secrets/seafile.env
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - seafile
      - caddy
    labels:
      caddy: seafile.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  seafile:
  seafile_mariadb:
  seafile_elasticsearch:

networks:
  seafile:
  caddy:
    external: true
