version: "3.9"

services:
  searx:
    image: searx/searx
    restart: unless-stopped
    volumes:
      - ../data/searx:/etc/searx
    environment:
      BASE_URL: https://searx.marcpartensky.com
    networks:
      - caddy
    labels:
      caddy: searx.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.searx.rule: Host(`searx.marcpartensky.com`)
      traefik.http.routers.searx.entrypoints: websecure
      traefik.http.routers.searx.tls.certresolver: tls
      traefik.http.services.searx.loadbalancer.server.port: 8080
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.searx.rule: Host(`searx.marcpartensky.com`)
        traefik.http.routers.searx.entrypoints: websecure
        traefik.http.routers.searx.tls.certresolver: tls
        traefik.http.services.searx.loadbalancer.server.port: 8080

# volumes:
#   searx:

networks:
  caddy:
    external: true
