version: "3.9"

services:
  sslh:
    image: marcpartensky/sslh
    restart: unless-stopped
    environment:
      # LISTEN_IP: 0.0.0.0
      # LISTEN_PORT: 443
      SSH_HOST: marcpartensky.com
      SSH_PORT: 22
      # OPENVPN_HOST: localhost
      # OPENVPN_PORT: 1194
      HTTPS_HOST: caddy
      HTTPS_PORT: 443
    ports:
      - "443:8443"
    # command: --tls=caddy:443 --ssh=marcpartensky.com:7022
    networks:
      - caddy
      # - bridge
    depends_on:
      - caddy
    healthcheck:
      # test: ["CMD-SHELL", "wget", "--no-check-certificate", "https://caddy:8443"]
      test: ["CMD-SHELL", "/usr/bin/curl", "http://caddy"]
      # interval: 30s
      # timeout: 5s
      # retries: 5

networks:
  caddy:
    external: true
