version: "3.9"
services:
  streamlit:
    image: aminehy/docker-streamlit-app:latest
    # command: "streamlit run src/main.py"
    ports:
      - "8501:8501"
    volumes:
      - streamlit:/usr/src/app/src

volumes:
  - streamlit
