version: "3.9"
services:
  # mariadb:
  #   image: docker.io/bitnami/mariadb:11.2
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_suitecrm
  #     - MARIADB_DATABASE=bitnami_suitecrm
  #     - MARIADB_PASSWORD=bitnami123
  #   volumes:
  #     - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: docker.io/bitnami/suitecrm:8
    env_file:
      - ../data/secrets/suitecrm.env
    volumes:
      - /srv/suitecrm:/bitnami/suitecrm
    networks:
      - postgres
      - caddy
    labels:
      traefik.enable: "true"
      traefik.http.routers.suitecrm.rule: >
        Host(`crm.marcpartensky.com`)
      traefik.http.routers.suitecrm.entrypoints: web
      traefik.http.services.suitecrm.loadbalancer.server.port: 8080

  # volumes:
  # mariadb_data:
  #   driver: local
  # suitecrm_data:
  #   driver: local
networks:
  postgres:
    external: true
  caddy:
    external: true
