version: "3.9"

services:
  swarmpit-db:
    image: couchdb:2.3.0
    volumes:
      - swarmpit-db:/opt/couchdb/data
    networks:
      - swarmpit
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        # reservations:
        #   cpus: '0.15'
        #   memory: 128M

volumes:
  swarmpit-db:

networks:
  swarmpit:
