version: "3.9"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - /srv:/srv
    # ports:
      # - 8384:8384
      # - 22000:22000/tcp
      # - 21027:21027/udp
    networks:
      - caddy
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncthing.rule: >
        Host(`syncthing.marcpartensky.com`)
      traefik.http.routers.syncthing.entrypoints: web
      # traefik.http.routers.syncthing.tls.certresolver: tls
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
      traefik.http.routers.syncthing.middlewares: ldap_auth
networks:
  caddy:
    external: true
