services:
  # ffsync:
  #   image: mozilla/syncserver:latest
  #   restart: unless-stopped
  #   env_file:
  #     - ../data/secrets/ffsync.env
  #   volumes:
  #     - /srv/ffsync:/data
  #   networks:
  #     - caddy
  #     - postgres
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.ffsync.rule: Host(`ffsync.marcpartensky.com`)
  #     traefik.http.routers.ffsync.entrypoints: web
  #     traefik.http.services.ffsync.loadbalancer.server.port: 5000
    # labels:
    #   - traefik.enable: true
    #   - traefik.backend: ffsync
    #   - traefik.frontend.rule: Host:firefoxsync.${DOMAINNAME}
    #   - traefik.port: 5000
    #   - traefik.docker.network: caddy

  # ffsync_db:
  #   image: postgres:alpine
  #   container_name: ffsync_db
  #   restart: unless-stopped
  #   networks:
  #       - ffsync_network
  #   environment:
  #     POSTGRES_DB: ${FFSYNC_DATABASE_DB}
  #     POSTGRES_USER: ${FFSYNC_DATABASE_USER}
  #     POSTGRES_PASSWORD: ${FFSYNC_DB_PASSWORD}

  # mock-fxa-server:
  #   image: app:build
  #   restart: "no"
  #   entrypoint: "sh scripts/start_mock_fxa_server.sh"
  #   environment:
  #     MOCK_FXA_SERVER_HOST: 0.0.0.0
  #     MOCK_FXA_SERVER_PORT: 6000

  syncserver:
    # NOTE: The naming in the rest of this repository has been updated to reflect the fact
    # that Syncstorage and Tokenserver are now part of one repository/server called
    # "Syncserver" (updated from "syncstorage-rs"). We keep the legacy naming below for
    # backwards compatibility with previous Docker images.
    image: mozilla/syncstorage-rs:latest
    restart: unless-stopped
    # depends_on:
    #   - sync-db
    #   - tokenserver-db
    env_file:
      - ../data/secrets/syncserver.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncserver.rule: Host(`syncserver.marcpartensky.com`)
      traefik.http.routers.syncserver.entrypoints: web
      traefik.http.services.syncserver.loadbalancer.server.port: 8000

networks:
  postgres:
    external: true
  caddy:
    external: true
