version: "3.9"
services:
  tableau:
    image: marcpartensky/tableau-server
    restart: unless-stopped
    env_file:
      - ../data/secrets/tableau.env
    networks:
      - caddy
    labels:
      caddy: tableau.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      traefik.enable: "true"
      traefik.http.routers.tableau.rule: Host(`tableau.marcpartensky.fr`)
      traefik.http.routers.tableau.entrypoints: websecure
      traefik.http.routers.tableau.tls.certresolver: tls
      traefik.http.services.tableau.loadbalancer.server.port: 8080

networks:
  caddy:
    external: true

# docker run \
# -e LICENSE_KEY=<key> \
# -e TABLEAU_USERNAME=<username> \
# -e TABLEAU_PASSWORD=<password> \
# --hostname=<static (internal) name of host machine> \
# -p 8080:8080 -d <Tableau Server in a Container image ID or tag>
