services:
  time-assistant:
    # image: docker.io/marcpartensky/time-assistant
    image: docker.io/marcpartensky/time-assistant:v13.0e90e4c.2025-03-18
    env_file:
      - ../data/secrets/time-assistant.env
    # volumes:
    #   - /srv/time-assistant:/bitnami/time-assistant
    networks:
      - postgres
    #   - caddy
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.routers.time-assistant.rule: >
    #     Host(`time-assistant.marcpartensky.com`)
    #   traefik.http.routers.time-assistant.entrypoints: web
    #   traefik.http.services.time-assistant.loadbalancer.server.port: 8000

networks:
  postgres:
    external: true
  # caddy:
  #   external: true
