version: "3.9"

services:
  front:
    image: marcpartensky/je-todoapp-react
    restart: unless-stopped
    environment:
      PORT: 80
      SPRING_API_URL: https://api.todolist.marcpartensky.com
    depends_on:
      - back
    networks:
      - caddy
    # entrypoint: ["/bin/sh", "-c", "'SPRING_API_URL=https://api.todolist.marcpartensky.com serve -s build'"]
    labels:
      caddy: todolist.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.front.rule: Host(`todolist.marcpartensky.com`)
      traefik.http.routers.front.entrypoints: websecure
      traefik.http.routers.front.tls.certresolver: tls
      traefik.http.services.front.loadbalancer.server.port: 80
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.front.rule: Host(`todolist.marcpartensky.com`)
        traefik.http.routers.front.entrypoints: websecure
        traefik.http.routers.front.tls.certresolver: tls
        traefik.http.services.front.loadbalancer.server.port: 80

  back:
    image: marcpartensky/je-todoapp-spring-api
    restart: unless-stopped
    env_file:
      - ../data/secrets/todolist.env
    environment:
      # PORT: 80
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks:
      - caddy
      - todolist
    labels:
      caddy: api.todolist.marcpartensky.com
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
      traefik.enable: "true"
      traefik.http.routers.back.rule: Host(`api.todolist.marcpartensky.com`)
      traefik.http.routers.back.entrypoints: websecure
      traefik.http.routers.back.tls.certresolver: tls
      traefik.http.services.back.loadbalancer.server.port: 8080
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.back.rule: Host(`api.todolist.marcpartensky.com`)
        traefik.http.routers.back.entrypoints: websecure
        traefik.http.routers.back.tls.certresolver: tls
        traefik.http.services.back.loadbalancer.server.port: 8080

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ../data/secrets/todolist.env
    networks:
      - todolist

volumes:
  postgres:

networks:
  todolist:
  caddy:
    external: true
