version: "3.9"

services:
  traefik:
    image: traefik
    restart: unless-stopped
    command:
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      # - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.file.filename=/dynamic.yaml # <== Referring to a dynamic configuration file
      # - --providers.docker.network=web # <== Operate on the docker network named web
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      - --api.insecure=false # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true
      - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
      ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.tls.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - --certificatesresolvers.tls.acme.email=marc.partensky@gmail.com
      - --certificatesresolvers.tls.acme.storage=/letsencrypt/acme.json # Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=DEBUG # <== Setting the level of the logs from traefik
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy
    volumes:
      - traefik_letsencrypt:/letsencrypt
      # - ../data/traefik/traefik.yml:/root/.config/traefik.yml # no configuration file
      # - ./data/traefik/dynamic.yaml:/dynamic.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`traefik.marcpartensky.com`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls.certresolver: tls
      traefik.docker.network: caddy
      traefik.http.middlewares.test-ldap-auth.plugin.ldapAuth.source: marcpartensky.com
      traefik.http.middlewares.test-ldap-auth.plugin.ldapAuth.baseDN: dc=marcpartensky,dc=com
      # traefik.http.routers.redirs.entrypoints: web
      # traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      # traefik.http.routers.redirs.middlewares: redirect-to-https
      # traefik.http.routers.redirs.rule: hostregexp(`{host:.+}`)

volumes:
  traefik_letsencrypt:

networks:
  caddy:
    external: true
