version: "3.9"
services:
  ssh-tunnel:
    image: kroniak/ssh-client
    network_mode: host
    entrypoint: ssh -NR 42072:localhost:42069 marc@fourche.org -p42069
    volumes:
      - ~/.ssh:/root/.ssh
