version: "3.9"
services:
  ssh-tunnel:
    image: kroniak/ssh-client
    network_mode: host
    entrypoint: ssh -NR 42069:localhost:22 debian@etienne-faviere.tech
    volumes:
      - ~/.ssh:/root/.ssh
