version: "3.9"
services:
  kuma:
    image:  louislam/uptime-kuma:1
    volumes:
      - kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.kuma.loadbalancer.server.port: 3001
        traefik.http.routers.kuma.rule: >
          Host(`uptime.marcpartensky.com`) || Host(`uptime.marcpartensky.fr`)
        traefik.http.routers.kuma.entrypoints: websecure
        traefik.http.routers.kuma.tls.certresolver: cloudflare
        traefik.http.routers.kuma.middlewares: ldap_auth

networks:
  caddy:
    external: true
volumes:
  kuma:
