version: "3.9"

services:
  valentin_website:
    image: valentincolin/website
    restart: unless-stopped
    environment:
      PRODUCTION: "True"
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - caddy
    labels:
      caddy: valentin-colin.fr
      caddy.reverse_proxy: "{{upstreams 80}}"
      traefik.enable: "true"
      traefik.http.routers.valentincolin_website.rule: Host(`valentin-colin.com`)
      traefik.http.routers.valentincolin_website.entrypoints: websecure
      traefik.http.routers.valentincolin_website.tls.certresolver: tls
      traefik.http.services.valentincolin_website.loadbalancer.server.port: 80

networks:
  caddy:
    external: true
