version: "3.9"
services:
  ldap_sync:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example.config.toml:/config.toml:ro
      # ./root.cert:/usr/src/vaultwarden_ldap/root.cert:ro
    environment:
      CONFIG_PATH: /config.toml
      RUST_BACKTRACE: 1
    depends_on:
      - vaultwarden
      - ldap

  vaultwarden:
    image: vaultwarden/server
    ports:
      - "8000:80"
    environment:
      ADMIN_TOKEN: admin
      SIGNUPS_ALLOWED: 'false'
      INVITATIONS_ALLOWED: 'true'

  ldap_admin:
    image: osixia/phpldapadmin
    ports:
      - 8001:80
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    depends_on:
      - ldap
