version: "3.9"
services:
  ldap_sync:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example.config.toml:/config.toml:ro
      # ./root.cert:/usr/src/vaultwarden_ldap/root.cert:ro
    environment:
      CONFIG_PATH: /config.toml
      RUST_BACKTRACE: 1
    depends_on:
      - vaultwarden

  vaultwarden:
    image: vaultwarden/server
    environment:
      ADMIN_TOKEN: admin
      SIGNUPS_ALLOWED: 'false'
      INVITATIONS_ALLOWED: 'true'
    networks:
      - caddy
    labels:
      caddy: vault.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      traefik.enable: "true"
      traefik.http.routers.gitea.rule: Host(`vault.marcpartensky.com`)
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.tls.certresolver: tls
      traefik.http.services.gitea.loadbalancer.server.port: 80

  ldap_admin:
    image: osixia/phpldapadmin
    ports:
      - 8001:80
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    depends_on:
      - ldap

networks:
  caddy:
    external: true
