#
# Please consult the `Deployment` section in the readme if you want to deploy
# this. You *need* to keep this nginx service, even if you have your own,
# otherwise the static files will not be served correctly! If you do remove
# it, configure yours similarly to what's in config/nginx.conf
# Also take a look at the "Static files" section in the .env file

services:
  wger:
    image: wger/server:latest
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   cache:
    #     condition: service_healthy
    env_file:
      - ../data/secrets/wger.env
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:stable
    volumes:
      - ../data/wger/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/wger/static:ro
      - media:/wger/media:ro
    ports:
      - "80:80"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5

  # cache:
  #   image: redis
  #   expose:
  #     - 6379
  #   healthcheck:
  #     test: redis-cli ping
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: unless-stopped

  celery_worker:
    image: wger/server:latest
    container_name: wger_celery_worker
    command: /start-worker
    env_file:
      - ./data/secrets/wger.env
    # depends_on:
    #   cache:
    #     condition: service_healthy
    #   db:
    #     condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5

  celery_beat:
    image: wger/server:latest
    command: /start-beat
    volumes:
      - celery-beat:/home/wger/beat/
    env_file:
      - ./config/.env
      - ./data/secrets/wger.env
    # depends_on:
    #   cache:
    #     condition: service_healthy

volumes:
  celery-beat:
  static:
  media:

networks:
  caddy:
    external: true
  postgres:
    external: true
