version: "3.9"
services:
  whoami:
    image: traefik/whoami
    networks:
      - caddy
    deploy:
      # replicas: 0
      labels:
        traefik.enable: "true"
        traefik.http.routers.whoami.rule: Host(`whoami.marcpartensky.fr`)
        # traefik.http.routers.whoami.rule: >
        #   Host(`whoami.marcpartensky.com`) || Host(`whoami.marcpartensky.fr`)
        traefik.http.routers.whoami.entrypoints: websecure
        traefik.http.routers.whoami.tls.certresolver: tls
        traefik.http.services.whoami.loadbalancer.server.port: 80
          # traefik.http.routers.whoami.middlewares: dynamic@docker
          # traefik.docker.lbswarm: "true"

networks:
  caddy:
    external: true
