services:
  whoami:
    image: "traefik/whoami"
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: true
        traefik.http.routers.whoami.rule: Host(`whoami.marcpartensky.com`)"
        traefik.http.routers.whoami.entrypoints: websecure

networks:
  caddy:
    external: true
