version: "3.9"
services:
  whoami:
    image: traefik/whoami
    networks:
      - caddy
  whoami2:
    image: traefik/whoami
    networks:
      - caddy
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami2.rule: >
        Host(`whoami2.marcpartensky.com`)
      traefik.http.routers.whoami2.entrypoints: web
      # traefik.http.routers.whoami.tls.certresolver: tls
      traefik.http.services.whoami2.loadbalancer.server.port: 80
      traefik.http.routers.whoami2.middlewares: cloudflare@file,remoteaddr@file
        # traefik.docker.lbswarm: "true"

networks:
  caddy:
    external: true
