version: "3.9"
services:
  wireguard:
    image: linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      # SERVERURL: marcpartensky.com
      SERVERURL: marcpartensky.fr
      SERVERPORT: 51820 #optional
      PEERS: 1 #optional
      PEERDNS: auto #optional
      INTERNAL_SUBNET: 10.13.13.0 #optional
      ALLOWEDIPS: 0.0.0.0/0 #optional
    volumes:
      # - /usr/src:/usr/src # location of kernel headers
      - ../data/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
