version: "3.9"

services:
  wordpress_oxivia:
    image: wordpress
    restart: unless-stopped
    networks:
      - caddy
      - wordpress
    env_file:
      - ../data/secrets/wordpress_oxivia.env
    volumes:
      - wordpress_oxivia:/var/www/html
    depends_on:
      - wordpress_oxivia_mysql
    labels:
      caddy: oxivia.wordpress.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.wordpress.rule: Host(`oxivia.wordpress.marcpartensky.com`)
      traefik.http.routers.wordpress.entrypoints: websecure
      traefik.http.routers.wordpress.tls.certresolver: tls
      traefik.http.services.wordpress.loadbalancer.server.port: 80

  wordpress_oxivia_mysql:
    image: mysql
    restart: unless-stopped
    env_file:
      - ../data/secrets/wordpress_oxivia.env
    networks:
      - wordpress
    volumes:
      - wordpress_oxivia_mysql:/var/lib/mysql
    command:
      --character-set-server=utf8_general_ci --collation-server=utf8_general_ci
    # healthcheck:
    #   test: CMD /bin/sh -c 'mysqladmin ping --user=$MYSQL_USER --password=$MYSQL_PASSWORD'


volumes:
  wordpress_oxivia:
  wordpress_oxivia_mysql:

networks:
  wordpress:
  caddy:
    external: true
