version: "3.9"

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    networks:
      - caddy
      - wordpress
    env_file:
      - ../data/secrets/wordpress.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress_mysql
    labels:
      caddy: wordpress.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.wordpress.rule: Host(`wordpress.marcpartensky.com`)
      traefik.http.routers.wordpress.entrypoints: websecure
      traefik.http.routers.wordpress.tls.certresolver: tls
      traefik.http.services.wordpress.loadbalancer.server.port: 80
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.wordpress.rule: Host(`wordpress.marcpartensky.com`)
        traefik.http.routers.wordpress.entrypoints: websecure
        traefik.http.routers.wordpress.tls.certresolver: tls
        traefik.http.services.wordpress.loadbalancer.server.port: 80

  wordpress_mysql:
    image: mysql
    restart: unless-stopped
    env_file:
      - ../data/secrets/wordpress.env
    networks:
      - wordpress
    volumes:
      - wordpress_mysql:/var/lib/mysql
    # healthcheck:
    #   test: CMD /bin/sh -c 'mysqladmin ping --user=$MYSQL_USER --password=$MYSQL_PASSWORD'
    #
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    env_file:
      - ../data/secrets/wordpress.env
    networks:
      - wordpress
    ports:
      - "8880:80"
    labels:
      caddy: phpmyadmin.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"

volumes:
  wordpress:
  wordpress_mysql:

networks:
  wordpress:
  caddy:
    external: true
