version: "3.9"

services:
  wordpress_je:
    image: wordpress
    restart: unless-stopped
    networks:
      - caddy
      - wordpress_je
    environment:
      WORDPRESS_DB_HOST: wordpress_je_mysql
    env_file:
      - ../data/secrets/wordpress_template.env
    volumes:
      - wordpress_je:/var/www/html
    depends_on:
      - wordpress_je_mysql
    labels:
      caddy: wordpress.je.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams}}"
      traefik.enable: "true"
      traefik.http.routers.wordpress.rule: Host(`wordpress.marcpartensky.com`)
      traefik.http.routers.wordpress.entrypoints: websecure
      traefik.http.routers.wordpress.tls.certresolver: tls
      traefik.http.services.wordpress.loadbalancer.server.port: 80

  wordpress_je_mysql:
    image: mysql
    restart: unless-stopped
    env_file:
      - ../data/secrets/wordpress_template.env
    networks:
      - wordpress_je
    volumes:
      - wordpress_je_mysql:/var/lib/mysql

volumes:
  wordpress_je:
  wordpress_je_mysql:

networks:
  wordpress_je:
  caddy:
    external: true
