services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.whatsupdocker.rule: >
        Host(`whatsupdocker.marcpartensky.com`)
      traefik.http.routers.whatsupdocker.entrypoints: web
      traefik.http.services.whatsupdocker.loadbalancer.server.port: 3000
      # traefik.http.middlewares.whatsupdocker.redirectscheme.scheme: https
      traefik.http.routers.whatsupdocker.middlewares: ldap_auth
networks:
  caddy:
    external: true
