version: "3.9"
services:
  yt-dlp:
    # container_name: ytdlp
    image: marcpartensky/yt-dlp
    restart: unless-stopped
    volumes:
      - ../data/yt-dlp:/root/downloads
      - ~/Videos/Youtube:/srv
    env_file:
      - ../data/secrets/yt-dlp.env
    network_mode: none

  webui:
    image: ghcr.io/marcopeocchi/yt-dlp-web-ui:latest
    restart: unless-stopped
    volumes:
      - ~/Videos/Youtube:/downloads
    networks:
      - caddy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.ytdlp.rule: >
          Host(`yt.marcpartensky.fr`) ||
          Host(`yt.marcpartensky.com`)
        traefik.http.routers.ytdlp.entrypoints: websecure
        traefik.http.routers.ytdlp.tls.certresolver: cloudflare
        traefik.http.services.ytdlp.loadbalancer.server.port: 3033

volumes:
  ytdlp:
networks:
  caddy:
    external: true
