version: "3.9"
services:
  yt-dlp:
    # container_name: ytdlp
    image: marcpartensky/yt-dlp
    restart: unless-stopped
    volumes:
      - ~/Videos/Youtube:/srv
    env_file:
      - ../data/secrets/yt-dlp.env
