version: '3.9'
services:
  gitea:
    image: gitea/gitea:1.14.6
    container_name: gitea
    restart: unless-stopped
    env_file: .env
    networks:
    - caddy
    - postgres
    volumes:
    - ssh:/data/git/.ssh
    - data:/data
    ports:
    - '42070:22'
volumes:
  data: null
  ssh: null
networks:
  postgres:
    external: true
  caddy:
    external: true
