version: '3.9'
services:
  traefik:
    image: docker.io/traefik:latest
    restart: unless-stopped
    env_file: .env
    networks:
    - caddy
    - ldap
    volumes:
    - ../../data/traefik:/etc/traefik
    - /srv/traefik:/config
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.marcpartensky.com`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.docker.network: caddy
    healthcheck:
      test: traefik healthcheck --ping

networks:
  ldap:
    external: true
  caddy:
    external: true
