version: '3.9'
services:
  pgweb:
    image: marcpartensky/pgweb
    container_name: pgweb
    restart: unless-stopped
    env_file: .env
    networks:
    - postgres
    - caddy
networks:
  postgres:
    external: true
  caddy:
    external: true
