name: Check docker compose files

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install make and docker-compose
        run: sudo apt install -y docker-compose make
      # - name: Check docker-compose files
      #   run: for file in `find services/*`; do docker-compose -f $file config > /dev/null; done
      - name: Merge to docker-compose.yml
        run: make merge
      - name: Validate docker-compose.yml
        run: docker-compose -f stacks/docker-compose.yml config
