name: Check docker compose files

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: apt update
      - name: Install docker-compose
        run: apt install -y docker-compose
      - name: Check docker-compose files
        run: for file in `find services` ; docker-compose -f $file config > /dev/null done
