name: Docker Swarm Deployed

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: apt-get install openssh-client -y
      - name: Setup ssh
        run: eval $(ssh-agent -s) && ssh-add <(echo $SSH_PRIVATE_KEY)
      - name: Deploy to Docker swarm
        run: ssh -o StrictHostKeyChecking=no $SSH_REMOTE docker swarm deploy -c vps.yml vps
