name: Docker Swarm Deployed

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: stack deploy --compose-file vps.yml vps
